#!/usr/bin/env python3
# Scaffold facebook_ads_v2_2026-09-01_to_2026-09-30.json (8 ads, mapeo de f-master).
# Copy es DRAFT — @f-master finaliza primaryText/headline antes del deploy de ads.
import json, datetime

PHONE = "(915) 995-9524"

ads = [
 dict(id="META-SEP-01", name="2×1 Social + Wine — Tag Your Glow Partner", week="Tuesdays Sep 1/8/15/22",
      objective="Conversions (bookings / calls)", funnel="Prospecting + retargeting",
      creativeDay=1, alternateCreativeDays=[8,15,22],
      audience="Women 25–55 near Cielo Vista Mall; social/plans interest; exclude recent 2×1 converters.",
      primaryTextA="Two facials. One glass of wine. Zero excuses. Tuesdays at Solace Skin Lab are 2×1 facials — bring your glow partner and get two free facials to share. Tag her and book before Tuesday fills.",
      primaryTextB="Make it a skincare girls' night. Every Tuesday: 2×1 facials, a glass of wine, and two free facials to share at Solace Skin Lab, El Paso.",
      headlineA="Tuesdays Were Made for Two", headlineB="2×1 Facials + Wine",
      description="Cielo Vista Mall • Bring your glow partner",
      cta="BOOK_NOW", destination="Call (915) 995-9524 or client booking page",
      optimization="Conversions; pin Tuesdays in flight.",
      compliance="21+ age restriction for wine imagery/messaging; confirm 2×1 terms before live."),
 dict(id="META-SEP-02", name="Last 2×1 Tuesday of September", week="Tuesday Sep 29",
      objective="Conversions (urgency)", funnel="Retargeting",
      creativeDay=29,
      audience="Warm audience: past engagers, video viewers, women 25–55; urgency message.",
      primaryTextA="This is the last 2×1 Tuesday of September. After this, you wait for October. 2×1 facials, wine, and two free facials to share — one more chance to bring your person.",
      primaryTextB="Last call for September's 2×1 Tuesday. Don't wait for October — book your glow partner and lock your Tuesday now.",
      headlineA="Last 2×1 Tuesday of September", headlineB="Book Before It's Gone",
      description="Cielo Vista Mall • Call (915) 995-9524",
      cta="CALL_NOW", destination="Call (915) 995-9524",
      optimization="Conversions; last-week flight.",
      compliance="21+ age restriction; urgency must reflect real availability."),
 dict(id="META-SEP-03", name="Luxury Skincare + FREE Facial · $64.99", week="Friday Sep 11",
      objective="Conversions", funnel="Prospecting",
      creativeDay=11,
      audience="Skincare-aware women 28–55; premium product intent.",
      primaryTextA="Get a free facial with the purchase of any luxury skincare product — only $64.99. Build a routine that actually fits your skin and leave with a professional facial on us.",
      primaryTextB="A luxury product that works between visits, plus a facial that renews your glow — $64.99 with a free facial included. Call for eligible products and terms.",
      headlineA="Free Facial With Luxury Skincare", headlineB="Luxury Skincare + Free Facial",
      description="Cielo Vista Mall • Call (915) 995-9524",
      cta="CALL_NOW", destination="Call (915) 995-9524 for terms",
      optimization="Conversions; value-stack messaging (not discount).",
      compliance="Confirm eligible products and terms; no price-as-discount framing."),
 dict(id="META-SEP-04", name="Luxury + Free Facial · $64.99 (variant)", week="Thursday Sep 24",
      objective="Conversions", funnel="Prospecting (creative test)",
      creativeDay=24,
      audience="Same as META-SEP-03; product-lifestyle creative variant A/B test.",
      primaryTextA="Your skincare should earn its place on your shelf — and right now it comes with a free facial. Purchase any luxury skincare product for just $64.99 and get a professional facial on us.",
      primaryTextB="Build the routine your skin has been asking for, and leave with a free facial. $64.99 luxury skincare + a professional facial on us.",
      headlineA="Luxury Skincare, Free Facial", headlineB="A Routine That Earns Its Place",
      description="Cielo Vista Mall • Call (915) 995-9524",
      cta="CALL_NOW", destination="Call (915) 995-9524",
      optimization="Conversions; test creative vs. offer lift.",
      compliance="Same offer terms as META-SEP-03."),
 dict(id="META-SEP-05", name="Microneedling for Men — Breakouts Don't End at 30", week="Sunday Sep 6",
      objective="Conversions (consults)", funnel="Prospecting (men)",
      creativeDay=6,
      audience="Men 30–55; acne/acne-scarring interest; El Paso area.",
      primaryTextA="Adult acne isn't a teenage problem — plenty of men deal with breakouts and the scarring that follows well past 30. Microneedling may help improve the appearance of acne-scarred skin over a series of treatments. Individual results vary.",
      primaryTextB="Breakouts don't end at 30. If acne scarring is still on your mind, microneedling may help improve its appearance over a series of sessions. Book a consult for an honest read.",
      headlineA="Breakouts Don't End at 30", headlineB="Microneedling for Men",
      description="El Paso • Book a consult",
      cta="BOOK_NOW", destination="Book consult / call (915) 995-9524",
      optimization="Conversions; men's audience test.",
      compliance="Individual results vary; no outcome guarantees."),
 dict(id="META-SEP-06", name="Microneedling for Men — Scalp Care Isn't Just for Hair", week="Thursday Sep 17",
      objective="Conversions (consults)", funnel="Prospecting (men)",
      creativeDay=17,
      audience="Men 35–60; hair-thinning interest.",
      primaryTextA="Healthy-looking hair starts at the scalp. Microneedling on the scalp may help support the appearance of fuller, healthier hair for men, as part of a personalized approach. Individual results vary.",
      primaryTextB="Scalp care isn't just for hair. Scalp microneedling may help support a healthier-looking scalp as part of a broader approach for men. Book a private consult.",
      headlineA="Scalp Care Isn't Just for Hair", headlineB="Scalp Microneedling for Men",
      description="El Paso • Private consult",
      cta="BOOK_NOW", destination="Book consult / call (915) 995-9524",
      optimization="Conversions; men's audience test.",
      compliance="Individual results vary; no outcome guarantees."),
 dict(id="META-SEP-07", name="Salmon DNA — Skin-Nourishing Science", week="Thursday Sep 3",
      objective="Conversions (consults)", funnel="Prospecting (education)",
      creativeDay=3,
      audience="Skincare-curious women 28–55; ingredient-driven.",
      primaryTextA="Salmon DNA (PDRN) is the ingredient quietly taking over med-spa facials — molecules that may help support the skin's natural repair and hydration. No, it won't smell like fish. Curious if it fits your skin? Ask how a Salmon DNA treatment works.",
      primaryTextB="The ingredient everyone asks about: Salmon DNA (PDRN) may help support skin repair and deep hydration. No price games — just good science. Ask how a Salmon DNA facial could fit your routine.",
      headlineA="Salmon DNA · Skin-Nourishing Science", headlineB="The Ingredient Everyone Asks About",
      description="El Paso • Ask how it works",
      cta="LEARN_MORE", destination="Ask / consult",
      optimization="Engagement → retargeting; educate then convert.",
      compliance="Benefits only — no price shown on Salmon DNA creatives."),
 dict(id="META-SEP-08", name="October Appointments Are Filling", week="Wednesday Sep 30",
      objective="Conversions (close)", funnel="Retargeting",
      creativeDay=30,
      audience="Warm audience: engagers, consult-no-shows, cart-abandoners.",
      primaryTextA="September's almost gone and October appointments are already filling. If you've been meaning to book that facial, consult, or injectables visit — this is your sign.",
      primaryTextB="October is filling. Lock in your facial, consult, or injectables appointment now while there's still room.",
      headlineA="October Appointments Are Filling", headlineB="Book Your October Spot",
      description="Cielo Vista Mall • Call (915) 995-9524",
      cta="CALL_NOW", destination="Call (915) 995-9524",
      optimization="Conversions; end-of-month close.",
      compliance="Scarcity must reflect real booking availability."),
]

monthlyStrategy = dict(
  primaryGoal="Generate qualified calls and consultation inquiries; build a reusable local retargeting audience.",
  budgetAllocation=[
    {"percent":"40%","segment":"Conversion — Tuesday 2×1 + wine","purpose":"Core booker; 5 Tuesdays of urgency + social hook."},
    {"percent":"20%","segment":"Bundle value $64.99 + free facial","purpose":"Value-stack offer, high intent."},
    {"percent":"20%","segment":"Microneedling for MEN (acne + scalp)","purpose":"White-space audience, strongest differentiator."},
    {"percent":"15%","segment":"Salmon DNA education","purpose":"Own the ingredient angle; feed retargeting."},
    {"percent":"5%","segment":"Retargeting / end-of-month close","purpose":"Capture warm intent."},
  ],
  audienceFramework="Local El Paso adults near Cielo Vista Mall; men's split for microneedling; women's social split for 2×1; 21+ for wine creatives.",
  weeklyFlight=[
    {"week":1,"dates":"Sep 1–7","focus":"2×1 launch + Salmon DNA education","actions":"Flight 2×1 + Salmon DNA + men's acne; start retargeting pools."},
    {"week":2,"dates":"Sep 8–14","focus":"Bundle $64.99 + 2×1","actions":"Launch bundle $64.99; continue 2×1."},
    {"week":3,"dates":"Sep 15–21","focus":"Men's scalp + mid-month 2×1","actions":"Launch scalp men's ad; test creative variants."},
    {"week":4,"dates":"Sep 22–30","focus":"Bundle variant + last 2×1 + close","actions":"A/B bundle creative; urgency close on 29–30."},
  ],
  measurement=["Calls & consult requests (primary)","Cost per booking","2×1 Tuesday fill rate","Men's audience CTR vs. women's","Retargeting pool size"],
  testingRules=["A/B value-stack ($64.99) vs. discount-style — keep value-stack","Test men's acne vs. scalp creative","Hold 21+ audience exclusions for wine creatives","Do not lead with % off or price-per-unit anywhere"],
)

out = dict(
  campaign="Solace Skin Lab — September 2026 (Dark Luxury)",
  period="2026-09-01 to 2026-09-30",
  platforms=["Facebook"],
  status="DRAFT — copy final pendiente @f-master",
  officialPhone=PHONE,
  location="Cielo Vista Mall, El Paso TX",
  monthlyStrategy=monthlyStrategy,
  ads=ads,
)

with open("facebook_ads_v2_2026-09-01_to_2026-09-30.json","w") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
print("OK: 8 ads -> facebook_ads_v2_2026-09-01_to_2026-09-30.json")
print("creativeDays:", [a['creativeDay'] for a in ads])