import copy
import json
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

ROOT = Path('/opt/data/solace-skin-lab')
old = json.loads((ROOT/'calendar_2026-07-24_to_2026-08-22.json').read_text(encoding='utf-8'))
by_day = {p['day']: p for p in old}
out_path = ROOT/'calendar_v2_2026-07-24_to_2026-08-22.json'

mapping = {1:1,2:16,3:2,4:4,5:5,6:10,7:7,8:8,9:9,10:10,11:11,12:12,13:13,14:10,15:15,16:16,17:17,18:18,19:12,20:20,21:21,22:22,23:23,24:28,25:25,26:5,27:14,28:16,29:29,30:30}
start = date(2026,7,24)

visuals = {
1: dict(type='Campaign', title='Real Skin. Smart Care.', imageTitle='REAL SKIN. SMART CARE.', imageScript='What is your skin asking for?', imageScene='Luminous full-bleed editorial portrait of a confident adult Latina woman with natural pores, fine lines and authentic skin texture in a bright refined med-spa; organic typography flows through open warm-ivory space without a rigid panel.'),
2: dict(type='LED', title='Illuminate Your Skin with LED', imageTitle='ILLUMINATE YOUR SKIN', imageScript='LED Light Therapy', imageScene='Edit the supplied real Solace photo of a client under a blue LED mask. Preserve the real patient and real device, blue light as the visual focus, and rebuild it as a luminous premium editorial post without unsupported clinical claims.', sourceAsset='/opt/data/images/upload_20260723_162825_5.png'),
3: dict(type='Education', title='Dry Skin vs. Dehydrated Skin', imageTitle='DRY OR DEHYDRATED?', imageScript='Oil and water are not the same', imageScene='Premium macro skincare editorial showing authentic hydrated and dry-looking skin texture with two elegant unbranded skincare vessels, luminous cream background, powder-blue water accent and warm ivory oil accent; educational but not diagram-heavy.'),
4: dict(type='Promotion', title='Luxury Skincare Offer — A', imageTitle='GET A FREE FACIAL', imageScript='Luxury skincare, extra care', imageOffer='WITH THE PURCHASE OF ANY LUXURY SKINCARE PRODUCT • ONLY $64.99', imageScene='Adult Latina client in a bright refined med-spa selecting one elegant unbranded luxury skincare bottle after a facial; natural pores, restrained retouching, soft window light, full-bleed premium editorial photography.'),
5: dict(type='Promotion', title='Tuesday 2×1 — Glow Together', imageTitle='TUESDAY 2×1', imageScript='Glow better together', imageOffer='WINE + 2 FREE FACIALS', imageScene='Use the supplied real Solace Tuesday facial image as authentic source. Preserve the two real adult clients under LED, replace every old price and neon graphic with a bright premium ivory, sage and powder-blue editorial layout; tasteful wine detail only, no party mood.', sourceAsset='/opt/data/images/upload_20260723_162825_9.jpeg'),
6: dict(type='BOTOX® Cosmetic', title='BOTOX® Cosmetic: Real Care', imageTitle='BOTOX® COSMETIC', imageScript='Refreshed, still you', imageScene='Use the supplied real Solace BOTOX® Cosmetic treatment photograph. Preserve the real adult client, provider, gloves, device and documentary treatment angle; improve crop and light without inventing credentials, outcomes or logos.', sourceAsset='/opt/data/images/upload_20260723_162825_6.jpeg'),
7: dict(type='Education', title='El Paso Sun Counts', imageTitle='EL PASO SUN COUNTS', imageScript='SPF belongs in the everyday routine', imageScene='Bright El Paso lifestyle scene with an adult Latina woman applying unbranded sunscreen before a short daytime outing; authentic skin, desert daylight, ivory clothing, warm terracotta and powder-blue accents.'),
8: dict(type='Facial', title='A Facial for Your Skin', imageTitle='A FACIAL FOR YOUR SKIN', imageScript='Personalized to today', imageScene='Close documentary facial treatment in a bright med-spa: trained Latina provider gently works on an adult Latina client, natural pores and correct hands, cream towels, rose-clay accent, calm believable technique.'),
9: dict(type='Engagement', title='Your August Skin Reset', imageTitle='YOUR AUGUST SKIN RESET', imageScript='Choose progress, not perfection', imageScene='Confident adult Latina woman in a luminous editorial portrait with natural texture and minimal makeup; dynamic typography wraps around the figure without crossing her face; optimistic ivory, sage and soft-peach palette.'),
10: dict(type='BOTOX® Cosmetic', title='Before BOTOX® Cosmetic', imageTitle='BEFORE BOTOX®', imageScript='Questions come first', imageScene='Use the supplied real Solace BOTOX® Cosmetic materials photograph as the documentary foundation. Preserve authentic supplies while cleaning the composition; do not expose private information, invent brands, or imply treatment outcomes.', sourceAsset='/opt/data/images/upload_20260723_162825_7.jpeg'),
11: dict(type='Dermaplaning', title='Dermaplaning', imageTitle='DERMAPLANING', imageScript='A smoother-looking finish', imageScene='Highly realistic dermaplaning treatment close-up: trained gloved provider holds skin taut and uses a sterile dermaplaning blade at a safe shallow angle on the outer cheek; no cuts, no blood, bright clinical room.'),
12: dict(type='Promotion', title='Tuesday 2×1 — Facial Tuesday', imageTitle='2×1 FACIAL TUESDAY', imageScript='Bring your glow partner', imageOffer='WINE + 2 FREE FACIALS', imageScene='Use the supplied real Solace image of two adult clients under LED. Preserve real people and equipment while replacing the old dark neon design with a distinct luminous soft-peach and sage editorial composition; no prices and no party atmosphere.', sourceAsset='/opt/data/images/upload_20260723_162825_10.jpeg'),
13: dict(type='Microneedling', title='Microneedling for Acne Scar Texture', imageTitle='ACNE SCAR TEXTURE', imageScript='A thoughtful approach', imageScene='Highly realistic safe microneedling treatment on the lower outer cheek of an adult Latina client with authentic mild acne-scar texture. Trained provider with two correctly gloved hands holds a cordless pen perpendicular, sterile cartridge flat on skin, far below the eye; no blood.'),
14: dict(type='BOTOX® Cosmetic', title='Real Treatment. Real Care.', imageTitle='REAL TREATMENT. REAL CARE.', imageScript='BOTOX® Cosmetic consultation', imageScene='Use the supplied real Solace BOTOX® Cosmetic procedure image. Preserve the real provider, adult client, hands, gloves and treatment posture; premium bright documentary crop, no invented credentials, promises or before-and-after claims.', sourceAsset='/opt/data/images/upload_20260723_162825_8.jpeg'),
15: dict(type='Trust', title='Care for the Skin You’re In', imageTitle='CARE FOR THE SKIN YOU’RE IN', imageScript='Real texture. Thoughtful care.', imageScene='Natural-light editorial portrait of an adult Latina woman around 45 with visible pores, expression lines, freckles and a confident relaxed expression; no age erasure or plastic retouching, warm ivory and rose-clay accents.'),
16: dict(type='LED', title='LED Light Therapy', imageTitle='LED LIGHT THERAPY', imageScript='Color-led facial care', imageScene='Edit the supplied real blue LED treatment photo into a new premium bright editorial composition. Preserve the real client and device, maintain correct eye coverage, add restrained powder-blue and sage accents, and avoid absolute clinical claims.', sourceAsset='/opt/data/images/upload_20260723_162825_5.png'),
17: dict(type='Education', title='Consistency Over Complexity', imageTitle='CONSISTENCY OVER COMPLEXITY', imageScript='A routine you can keep', imageScene='Luminous editorial flat lay with exactly three elegant unbranded skincare products, folded cream towel and subtle weekly rhythm cues; no labels or extra writing, sage and pale-peach accents.'),
18: dict(type='Microneedling', title='Microneedling for Fine Lines and Texture', imageTitle='FINE LINES & TEXTURE', imageScript='Microneedling consultation', imageScene='Safe realistic microneedling close-up on the outer cheek of an adult Latina woman in her late 40s with natural fine lines. Pen perpendicular, correct gloves and cartridge, away from eyes and lips, no blood, restrained redness only.'),
19: dict(type='Promotion', title='Tuesday 2×1 Facials — Evening Edition', imageTitle='TUESDAY 2×1 FACIALS', imageScript='An elevated Tuesday together', imageOffer='WINE + 2 FREE FACIALS', imageScene='Two adult Latina friends enjoying a refined evening facial experience in a warm luminous med-spa, tasteful wine glasses discreetly in the background, ivory and muted terracotta lighting, sophisticated not nightclub-like, no visible alcohol consumption during treatment.'),
20: dict(type='Microneedling', title='Scalp Microneedling Consultation', imageTitle='SCALP MICRONEEDLING', imageScript='A personalized scalp approach', imageScene='Private realistic scalp microneedling consultation and safe treatment. Trained gloved provider parts an adult Latina client’s hair and holds a recognizable pen perpendicular to the scalp at the part line; no blood and no promise of hair growth.'),
21: dict(type='JUVÉDERM®', title='JUVÉDERM® Lip Filler Consultation', imageTitle='JUVÉDERM® LIP FILLER', imageScript='Balance, beautifully yours', imageScene='Bright realistic lip-filler consultation with an adult Latina client examining her natural lip proportions in a hand mirror while a provider listens; no needle visible, no exaggerated lips, authentic texture, ivory and blush palette.'),
22: dict(type='BOTOX® Cosmetic', title='Ask Before You Treat', imageTitle='ASK BEFORE YOU TREAT', imageScript='BOTOX® Cosmetic questions welcome', imageScene='Use the supplied authentic BOTOX® Cosmetic materials photo as the base for a clean editorial FAQ composition distinct from day 10. Preserve real supplies, remove legible private or product-label text, and avoid invented claims or credentials.', sourceAsset='/opt/data/images/upload_20260723_162825_7.jpeg'),
23: dict(type='Local Education', title='Desert Skin Needs Support', imageTitle='DESERT SKIN NEEDS SUPPORT', imageScript='Care shaped by El Paso', imageScene='Luminous El Paso lifestyle portrait of an adult Latina woman in soft desert morning light, natural pores, light clothing and sun hat, warm terracotta, sage and powder-blue landscape accents.'),
24: dict(type='Trust', title='Prepared with Care', imageTitle='PREPARED WITH CARE', imageScript='Details shape the experience', imageScene='Use the supplied real clinical materials photo as an authentic preparation foundation. Recompose into a clean bright flat lay emphasizing organization, sealed hygienic supplies and attention to detail; no claims, prices, labels or credentials.', sourceAsset='/opt/data/images/upload_20260723_162825_7.jpeg'),
25: dict(type='Promotion', title='Luxury Skincare Offer — B', imageTitle='GET A FREE FACIAL', imageScript='Your skincare comes with care', imageOffer='WITH THE PURCHASE OF ANY LUXURY SKINCARE PRODUCT • ONLY $64.99', imageScene='Distinct second offer creative: bright premium vanity scene with an adult Latina client after a facial selecting one elegant unbranded skincare bottle; full-bleed photography, pale peach, sage and ivory, no reuse of the pilot composition.'),
26: dict(type='Promotion', title='Last Tuesday to Glow 2×1', imageTitle='LAST TUESDAY TO GLOW 2×1', imageScript='Make this Tuesday yours', imageOffer='WINE + 2 FREE FACIALS', imageScene='Use the supplied real Solace image of two clients under LED as the authentic base. Preserve real people and equipment, create a completely new bright editorial crop with powder-blue, rose-clay and ivory typography; no old prices, no neon flyer style.', sourceAsset='/opt/data/images/upload_20260723_162825_9.jpeg'),
27: dict(type='Microneedling', title='Scar Texture Consultation', imageTitle='SCAR TEXTURE CONSULTATION', imageScript='Every scar deserves an individual look', imageScene='Documentary med-spa evaluation of a small fully healed cheek scar on an adult Latina client. Provider examines safely under soft clinical light; a microneedling pen is prepared nearby but not shown over an unsuitable area; no blood or dramatic damage.'),
28: dict(type='Facial + LED', title='Complete Facial + LED', imageTitle='COMPLETE FACIAL + LED', imageScript='A calm, complete experience', imageScene='Edit the supplied real blue LED facial photo into a premium service hero. Preserve the real client and authentic LED mask; show the facial experience through elegant cream towel and treatment-room context, bright editorial typography, no unsupported color-benefit claims.', sourceAsset='/opt/data/images/upload_20260723_162825_5.png'),
29: dict(type='Engagement', title='Small Skin Wins Count', imageTitle='SMALL SKIN WINS COUNT', imageScript='Progress lives in the everyday', imageScene='Spontaneous luminous portrait of an adult Latina woman celebrating a simple skincare routine win near a sunlit vanity, natural smile and texture, optimistic sage, powder-blue and soft-peach accents.'),
30: dict(type='Conversion', title='Your Next Step Starts Here', imageTitle='YOUR NEXT STEP STARTS HERE', imageScript='Clear information. Personalized care.', imageScene='Documentary consultation between a Latina professional and an adult Latina client in a bright med-spa, both seated and listening, natural expressions, warm ivory architecture and a clear welcoming visual path forward.'),
}

copy_overrides = {
2: dict(hook='Curious about LED Light Therapy without the hype?', body='LED Light Therapy can be discussed as a gentle, technology-forward complement to a personalized facial experience. The right option depends on your skin, goals, and the services available at Solace.', desire='A calm consultation can help you understand where LED may fit without relying on absolute promises.', cta='Save this post and call (915) 995-9524 to ask about LED Light Therapy.', hashtags='#LEDLightTherapy #ElPasoFacial #SolaceSkinLab #RealSkin #MedSpaElPaso'),
6: dict(hook='Real confidence starts with seeing the process—not a promise.', body='A BOTOX® Cosmetic consultation should include your goals, natural facial movement, suitability, potential risks, and realistic expectations before treatment is considered.', desire='Explore whether a measured approach may fit your goals while keeping your expression recognizably yours; individual results vary.', cta='Call (915) 995-9524 to schedule a BOTOX® Cosmetic consultation.', hashtags='#BOTOXCosmetic #ElPasoBOTOX #RealCare #SolaceSkinLab #ConsultationFirst'),
10: dict(hook='The best time to ask a BOTOX® Cosmetic question is before treatment.', body='Bring your questions about natural movement, timing, suitability, potential risks, aftercare, and what individual results may look like. A consultation should create clarity before any decision.', desire='Feeling informed helps you choose your next step with realistic expectations and less pressure.', cta='Save your questions and call (915) 995-9524 to schedule a consultation.', hashtags='#BeforeBOTOX #BOTOXCosmetic #AskQuestions #SolaceSkinLab #ElPasoMedSpa'),
14: dict(hook='Authentic treatment care is built on technique, communication, and realistic expectations.', body='This real Solace treatment moment reflects the conversation and professional preparation behind BOTOX® Cosmetic. Suitability, potential risks, treatment needs, and outcomes differ for every individual.', desire='A consultation can help determine whether a subtle approach is appropriate for your goals.', cta='Call (915) 995-9524 to book a BOTOX® Cosmetic consultation.', hashtags='#BOTOXCosmetic #RealTreatment #ElPasoMedSpa #SolaceSkinLab #Consultation'),
19: dict(hook='Your Tuesday plans just found a more relaxing direction.', body='TUESDAY 2×1 with WINE + 2 FREE FACIALS. Share an elevated self-care experience with your favorite person. Call for full terms, availability, restrictions, and wine eligibility for guests 21+.', desire='Make space to reconnect, unwind, and enjoy the experience together.', cta='Call (915) 995-9524 to confirm complete terms and reserve.', hashtags='#TuesdayFacials #TwoForOne #GlowTogether #SolaceSkinLab #ElPasoBeauty'),
22: dict(hook='Before BOTOX® Cosmetic, every question deserves a clear answer.', body='Ask about suitability, expected movement, potential risks, preparation, aftercare, timeline, and how individual outcomes can vary. Informed decisions begin with an honest consultation.', desire='Clear information can help you feel prepared rather than pressured.', cta='Send us your BOTOX® Cosmetic question or call (915) 995-9524.', hashtags='#AskBeforeYouTreat #BOTOXCosmetic #InformedCare #SolaceSkinLab #ElPasoMedSpa'),
24: dict(hook='Trust is shaped by the details you may not see during treatment.', body='Organized supplies, a prepared room, hygienic handling, attentive communication, and a clear plan all contribute to a more thoughtful client experience.', desire='Preparation helps care feel calm, intentional, and centered on you.', cta='Call (915) 995-9524 to learn more about the consultation process.', hashtags='#PreparedWithCare #BehindTheScenes #SolaceSkinLab #ElPasoMedSpa #ClientExperience'),
26: dict(hook='One last Tuesday invitation: bring the person you glow best with.', body='LAST TUESDAY TO GLOW 2×1 with WINE + 2 FREE FACIALS. Call for full terms, availability, restrictions, and wine eligibility for guests 21+.', desire='Turn the final Tuesday of this campaign into shared time for self-care.', cta='Call (915) 995-9524 to confirm complete terms and reserve.', hashtags='#LastTuesdayToGlow #TwoForOneFacials #SolaceSkinLab #ElPasoFacial #GlowTogether'),
27: dict(hook='A healed scar deserves an individual evaluation—not a one-size-fits-all promise.', body='Microneedling may be discussed for the appearance of certain fully healed scars and uneven texture. Suitability depends on scar type, location, skin history, and professional assessment; results vary.', desire='A consultation can set realistic expectations and identify whether this approach fits your skin.', cta='Call (915) 995-9524 to schedule a scar-texture evaluation.', hashtags='#ScarTexture #Microneedling #SkinConsultation #SolaceSkinLab #ElPasoMedSpa'),
28: dict(hook='A facial can feel even more complete when technology fits the plan.', body='Ask about pairing a personalized facial with LED Light Therapy as part of a calm, customized experience. Availability and suitability depend on your needs and the services offered.', desire='Enjoy thoughtful skincare and a relaxing technology-forward finish without exaggerated promises.', cta='Call (915) 995-9524 to ask about Facial + LED availability.', hashtags='#FacialAndLED #LEDLightTherapy #ElPasoFacial #SolaceSkinLab #SmartCare'),
}

posts=[]
for day in range(1,31):
    p=copy.deepcopy(by_day[mapping[day]])
    d=start+timedelta(days=day-1)
    p['day']=day
    p['date']=d.strftime('%a, %b %-d')
    hour=16 if d.weekday()>=5 else 15
    p['scheduledAt']=datetime(d.year,d.month,d.day,hour,tzinfo=timezone.utc).isoformat().replace('+00:00','Z')
    p.update(visuals[day])
    p.update(copy_overrides.get(day,{}))
    if 'imageOffer' not in visuals[day]:
        p.pop('imageOffer',None)
    posts.append(p)

out_path.write_text(json.dumps(posts,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print(out_path)
